[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
dice = "5GEGV7oBhx4XWBsTQYoWWRdaELNN7hmt5cZ8vQZ4W65r"

[programs.devnet]
dice = "5GEGV7oBhx4XWBsTQYoWWRdaELNN7hmt5cZ8vQZ4W65r"

[programs.testnet]
dice = "5GEGV7oBhx4XWBsTQYoWWRdaELNN7hmt5cZ8vQZ4W65r"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
#cluster = "https://api.devnet.solana.com"
#cluster = "https://api.testnet.solana.com"
wallet = "~/.config/solana/id.json"

[scripts]
#test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/dice.ts"
