[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
dice = "7Ah8WAJw7CDxwbPQono7rKaRAmZ4ymjguouz1CfHScXY"

[programs.devnet]
dice = "7Ah8WAJw7CDxwbPQono7rKaRAmZ4ymjguouz1CfHScXY"

[programs.testnet]
dice = "7Ah8WAJw7CDxwbPQono7rKaRAmZ4ymjguouz1CfHScXY"

[registry]
url = "https://api.apr.dev"

[provider]
#cluster = "Localnet"
#cluster = "https://api.devnet.solana.com"
cluster = "https://api.testnet.solana.com"
wallet = "~/.config/solana/id.json"

[scripts]
#test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/dice.ts"
